# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mule/Documents/Calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mule/Documents/Calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mule/Documents/Calculator/CMakeFiles /home/mule/Documents/Calculator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mule/Documents/Calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Calculator

# Build rule for target.
Calculator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Calculator
.PHONY : Calculator

# fast build rule for target.
Calculator/fast:
	$(MAKE) -f CMakeFiles/Calculator.dir/build.make CMakeFiles/Calculator.dir/build
.PHONY : Calculator/fast

#=============================================================================
# Target rules for targets named LUFA_USB

# Build rule for target.
LUFA_USB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LUFA_USB
.PHONY : LUFA_USB

# fast build rule for target.
LUFA_USB/fast:
	$(MAKE) -f CMakeFiles/LUFA_USB.dir/build.make CMakeFiles/LUFA_USB.dir/build
.PHONY : LUFA_USB/fast

#=============================================================================
# Target rules for targets named LUFA_USB-atmega32u4

# Build rule for target.
LUFA_USB-atmega32u4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LUFA_USB-atmega32u4
.PHONY : LUFA_USB-atmega32u4

# fast build rule for target.
LUFA_USB-atmega32u4/fast:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/build
.PHONY : LUFA_USB-atmega32u4/fast

#=============================================================================
# Target rules for targets named Calculator-atmega32u4

# Build rule for target.
Calculator-atmega32u4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Calculator-atmega32u4
.PHONY : Calculator-atmega32u4

# fast build rule for target.
Calculator-atmega32u4/fast:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/build
.PHONY : Calculator-atmega32u4/fast

#=============================================================================
# Target rules for targets named erase_program

# Build rule for target.
erase_program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erase_program
.PHONY : erase_program

# fast build rule for target.
erase_program/fast:
	$(MAKE) -f CMakeFiles/erase_program.dir/build.make CMakeFiles/erase_program.dir/build
.PHONY : erase_program/fast

c_lib/Battery_Monitor.o: c_lib/Battery_Monitor.cpp.o

.PHONY : c_lib/Battery_Monitor.o

# target to build an object file
c_lib/Battery_Monitor.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Battery_Monitor.cpp.o
.PHONY : c_lib/Battery_Monitor.cpp.o

c_lib/Battery_Monitor.i: c_lib/Battery_Monitor.cpp.i

.PHONY : c_lib/Battery_Monitor.i

# target to preprocess a source file
c_lib/Battery_Monitor.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Battery_Monitor.cpp.i
.PHONY : c_lib/Battery_Monitor.cpp.i

c_lib/Battery_Monitor.s: c_lib/Battery_Monitor.cpp.s

.PHONY : c_lib/Battery_Monitor.s

# target to generate assembly for a file
c_lib/Battery_Monitor.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Battery_Monitor.cpp.s
.PHONY : c_lib/Battery_Monitor.cpp.s

c_lib/Controller.o: c_lib/Controller.cpp.o

.PHONY : c_lib/Controller.o

# target to build an object file
c_lib/Controller.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Controller.cpp.o
.PHONY : c_lib/Controller.cpp.o

c_lib/Controller.i: c_lib/Controller.cpp.i

.PHONY : c_lib/Controller.i

# target to preprocess a source file
c_lib/Controller.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Controller.cpp.i
.PHONY : c_lib/Controller.cpp.i

c_lib/Controller.s: c_lib/Controller.cpp.s

.PHONY : c_lib/Controller.s

# target to generate assembly for a file
c_lib/Controller.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Controller.cpp.s
.PHONY : c_lib/Controller.cpp.s

c_lib/EEPROM.o: c_lib/EEPROM.cpp.o

.PHONY : c_lib/EEPROM.o

# target to build an object file
c_lib/EEPROM.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/EEPROM.cpp.o
.PHONY : c_lib/EEPROM.cpp.o

c_lib/EEPROM.i: c_lib/EEPROM.cpp.i

.PHONY : c_lib/EEPROM.i

# target to preprocess a source file
c_lib/EEPROM.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/EEPROM.cpp.i
.PHONY : c_lib/EEPROM.cpp.i

c_lib/EEPROM.s: c_lib/EEPROM.cpp.s

.PHONY : c_lib/EEPROM.s

# target to generate assembly for a file
c_lib/EEPROM.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/EEPROM.cpp.s
.PHONY : c_lib/EEPROM.cpp.s

c_lib/Encoder.o: c_lib/Encoder.cpp.o

.PHONY : c_lib/Encoder.o

# target to build an object file
c_lib/Encoder.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Encoder.cpp.o
.PHONY : c_lib/Encoder.cpp.o

c_lib/Encoder.i: c_lib/Encoder.cpp.i

.PHONY : c_lib/Encoder.i

# target to preprocess a source file
c_lib/Encoder.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Encoder.cpp.i
.PHONY : c_lib/Encoder.cpp.i

c_lib/Encoder.s: c_lib/Encoder.cpp.s

.PHONY : c_lib/Encoder.s

# target to generate assembly for a file
c_lib/Encoder.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Encoder.cpp.s
.PHONY : c_lib/Encoder.cpp.s

c_lib/Filter.o: c_lib/Filter.cpp.o

.PHONY : c_lib/Filter.o

# target to build an object file
c_lib/Filter.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Filter.cpp.o
.PHONY : c_lib/Filter.cpp.o

c_lib/Filter.i: c_lib/Filter.cpp.i

.PHONY : c_lib/Filter.i

# target to preprocess a source file
c_lib/Filter.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Filter.cpp.i
.PHONY : c_lib/Filter.cpp.i

c_lib/Filter.s: c_lib/Filter.cpp.s

.PHONY : c_lib/Filter.s

# target to generate assembly for a file
c_lib/Filter.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Filter.cpp.s
.PHONY : c_lib/Filter.cpp.s

c_lib/I2C_MPU6050.o: c_lib/I2C_MPU6050.cpp.o

.PHONY : c_lib/I2C_MPU6050.o

# target to build an object file
c_lib/I2C_MPU6050.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/I2C_MPU6050.cpp.o
.PHONY : c_lib/I2C_MPU6050.cpp.o

c_lib/I2C_MPU6050.i: c_lib/I2C_MPU6050.cpp.i

.PHONY : c_lib/I2C_MPU6050.i

# target to preprocess a source file
c_lib/I2C_MPU6050.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/I2C_MPU6050.cpp.i
.PHONY : c_lib/I2C_MPU6050.cpp.i

c_lib/I2C_MPU6050.s: c_lib/I2C_MPU6050.cpp.s

.PHONY : c_lib/I2C_MPU6050.s

# target to generate assembly for a file
c_lib/I2C_MPU6050.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/I2C_MPU6050.cpp.s
.PHONY : c_lib/I2C_MPU6050.cpp.s

c_lib/MEGN540_MessageHandeling.o: c_lib/MEGN540_MessageHandeling.cpp.o

.PHONY : c_lib/MEGN540_MessageHandeling.o

# target to build an object file
c_lib/MEGN540_MessageHandeling.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MEGN540_MessageHandeling.cpp.o
.PHONY : c_lib/MEGN540_MessageHandeling.cpp.o

c_lib/MEGN540_MessageHandeling.i: c_lib/MEGN540_MessageHandeling.cpp.i

.PHONY : c_lib/MEGN540_MessageHandeling.i

# target to preprocess a source file
c_lib/MEGN540_MessageHandeling.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MEGN540_MessageHandeling.cpp.i
.PHONY : c_lib/MEGN540_MessageHandeling.cpp.i

c_lib/MEGN540_MessageHandeling.s: c_lib/MEGN540_MessageHandeling.cpp.s

.PHONY : c_lib/MEGN540_MessageHandeling.s

# target to generate assembly for a file
c_lib/MEGN540_MessageHandeling.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MEGN540_MessageHandeling.cpp.s
.PHONY : c_lib/MEGN540_MessageHandeling.cpp.s

c_lib/MPU6050.o: c_lib/MPU6050.cpp.o

.PHONY : c_lib/MPU6050.o

# target to build an object file
c_lib/MPU6050.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MPU6050.cpp.o
.PHONY : c_lib/MPU6050.cpp.o

c_lib/MPU6050.i: c_lib/MPU6050.cpp.i

.PHONY : c_lib/MPU6050.i

# target to preprocess a source file
c_lib/MPU6050.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MPU6050.cpp.i
.PHONY : c_lib/MPU6050.cpp.i

c_lib/MPU6050.s: c_lib/MPU6050.cpp.s

.PHONY : c_lib/MPU6050.s

# target to generate assembly for a file
c_lib/MPU6050.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MPU6050.cpp.s
.PHONY : c_lib/MPU6050.cpp.s

c_lib/Matrix.o: c_lib/Matrix.cpp.o

.PHONY : c_lib/Matrix.o

# target to build an object file
c_lib/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Matrix.cpp.o
.PHONY : c_lib/Matrix.cpp.o

c_lib/Matrix.i: c_lib/Matrix.cpp.i

.PHONY : c_lib/Matrix.i

# target to preprocess a source file
c_lib/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Matrix.cpp.i
.PHONY : c_lib/Matrix.cpp.i

c_lib/Matrix.s: c_lib/Matrix.cpp.s

.PHONY : c_lib/Matrix.s

# target to generate assembly for a file
c_lib/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Matrix.cpp.s
.PHONY : c_lib/Matrix.cpp.s

c_lib/MotorPWM.o: c_lib/MotorPWM.cpp.o

.PHONY : c_lib/MotorPWM.o

# target to build an object file
c_lib/MotorPWM.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MotorPWM.cpp.o
.PHONY : c_lib/MotorPWM.cpp.o

c_lib/MotorPWM.i: c_lib/MotorPWM.cpp.i

.PHONY : c_lib/MotorPWM.i

# target to preprocess a source file
c_lib/MotorPWM.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MotorPWM.cpp.i
.PHONY : c_lib/MotorPWM.cpp.i

c_lib/MotorPWM.s: c_lib/MotorPWM.cpp.s

.PHONY : c_lib/MotorPWM.s

# target to generate assembly for a file
c_lib/MotorPWM.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/MotorPWM.cpp.s
.PHONY : c_lib/MotorPWM.cpp.s

c_lib/Ring_Buffer.o: c_lib/Ring_Buffer.cpp.o

.PHONY : c_lib/Ring_Buffer.o

# target to build an object file
c_lib/Ring_Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Ring_Buffer.cpp.o
.PHONY : c_lib/Ring_Buffer.cpp.o

c_lib/Ring_Buffer.i: c_lib/Ring_Buffer.cpp.i

.PHONY : c_lib/Ring_Buffer.i

# target to preprocess a source file
c_lib/Ring_Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Ring_Buffer.cpp.i
.PHONY : c_lib/Ring_Buffer.cpp.i

c_lib/Ring_Buffer.s: c_lib/Ring_Buffer.cpp.s

.PHONY : c_lib/Ring_Buffer.s

# target to generate assembly for a file
c_lib/Ring_Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Ring_Buffer.cpp.s
.PHONY : c_lib/Ring_Buffer.cpp.s

c_lib/SerialIO.o: c_lib/SerialIO.cpp.o

.PHONY : c_lib/SerialIO.o

# target to build an object file
c_lib/SerialIO.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/SerialIO.cpp.o
.PHONY : c_lib/SerialIO.cpp.o

c_lib/SerialIO.i: c_lib/SerialIO.cpp.i

.PHONY : c_lib/SerialIO.i

# target to preprocess a source file
c_lib/SerialIO.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/SerialIO.cpp.i
.PHONY : c_lib/SerialIO.cpp.i

c_lib/SerialIO.s: c_lib/SerialIO.cpp.s

.PHONY : c_lib/SerialIO.s

# target to generate assembly for a file
c_lib/SerialIO.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/SerialIO.cpp.s
.PHONY : c_lib/SerialIO.cpp.s

c_lib/Task_Management.o: c_lib/Task_Management.cpp.o

.PHONY : c_lib/Task_Management.o

# target to build an object file
c_lib/Task_Management.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Task_Management.cpp.o
.PHONY : c_lib/Task_Management.cpp.o

c_lib/Task_Management.i: c_lib/Task_Management.cpp.i

.PHONY : c_lib/Task_Management.i

# target to preprocess a source file
c_lib/Task_Management.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Task_Management.cpp.i
.PHONY : c_lib/Task_Management.cpp.i

c_lib/Task_Management.s: c_lib/Task_Management.cpp.s

.PHONY : c_lib/Task_Management.s

# target to generate assembly for a file
c_lib/Task_Management.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Task_Management.cpp.s
.PHONY : c_lib/Task_Management.cpp.s

c_lib/Timing.o: c_lib/Timing.cpp.o

.PHONY : c_lib/Timing.o

# target to build an object file
c_lib/Timing.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Timing.cpp.o
.PHONY : c_lib/Timing.cpp.o

c_lib/Timing.i: c_lib/Timing.cpp.i

.PHONY : c_lib/Timing.i

# target to preprocess a source file
c_lib/Timing.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Timing.cpp.i
.PHONY : c_lib/Timing.cpp.i

c_lib/Timing.s: c_lib/Timing.cpp.s

.PHONY : c_lib/Timing.s

# target to generate assembly for a file
c_lib/Timing.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/Timing.cpp.s
.PHONY : c_lib/Timing.cpp.s

c_lib/USB_Config/Descriptors.o: c_lib/USB_Config/Descriptors.c.o

.PHONY : c_lib/USB_Config/Descriptors.o

# target to build an object file
c_lib/USB_Config/Descriptors.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.o
.PHONY : c_lib/USB_Config/Descriptors.c.o

c_lib/USB_Config/Descriptors.i: c_lib/USB_Config/Descriptors.c.i

.PHONY : c_lib/USB_Config/Descriptors.i

# target to preprocess a source file
c_lib/USB_Config/Descriptors.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.i
.PHONY : c_lib/USB_Config/Descriptors.c.i

c_lib/USB_Config/Descriptors.s: c_lib/USB_Config/Descriptors.c.s

.PHONY : c_lib/USB_Config/Descriptors.s

# target to generate assembly for a file
c_lib/USB_Config/Descriptors.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.s
.PHONY : c_lib/USB_Config/Descriptors.c.s

c_lib/ZoomieZumo.o: c_lib/ZoomieZumo.cpp.o

.PHONY : c_lib/ZoomieZumo.o

# target to build an object file
c_lib/ZoomieZumo.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/ZoomieZumo.cpp.o
.PHONY : c_lib/ZoomieZumo.cpp.o

c_lib/ZoomieZumo.i: c_lib/ZoomieZumo.cpp.i

.PHONY : c_lib/ZoomieZumo.i

# target to preprocess a source file
c_lib/ZoomieZumo.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/ZoomieZumo.cpp.i
.PHONY : c_lib/ZoomieZumo.cpp.i

c_lib/ZoomieZumo.s: c_lib/ZoomieZumo.cpp.s

.PHONY : c_lib/ZoomieZumo.s

# target to generate assembly for a file
c_lib/ZoomieZumo.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/ZoomieZumo.cpp.s
.PHONY : c_lib/ZoomieZumo.cpp.s

c_lib/analog.o: c_lib/analog.c.o

.PHONY : c_lib/analog.o

# target to build an object file
c_lib/analog.c.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/analog.c.o
.PHONY : c_lib/analog.c.o

c_lib/analog.i: c_lib/analog.c.i

.PHONY : c_lib/analog.i

# target to preprocess a source file
c_lib/analog.c.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/analog.c.i
.PHONY : c_lib/analog.c.i

c_lib/analog.s: c_lib/analog.c.s

.PHONY : c_lib/analog.s

# target to generate assembly for a file
c_lib/analog.c.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/analog.c.s
.PHONY : c_lib/analog.c.s

c_lib/print.o: c_lib/print.cpp.o

.PHONY : c_lib/print.o

# target to build an object file
c_lib/print.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/print.cpp.o
.PHONY : c_lib/print.cpp.o

c_lib/print.i: c_lib/print.cpp.i

.PHONY : c_lib/print.i

# target to preprocess a source file
c_lib/print.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/print.cpp.i
.PHONY : c_lib/print.cpp.i

c_lib/print.s: c_lib/print.cpp.s

.PHONY : c_lib/print.s

# target to generate assembly for a file
c_lib/print.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/print.cpp.s
.PHONY : c_lib/print.cpp.s

c_lib/state_space_control.o: c_lib/state_space_control.cpp.o

.PHONY : c_lib/state_space_control.o

# target to build an object file
c_lib/state_space_control.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/state_space_control.cpp.o
.PHONY : c_lib/state_space_control.cpp.o

c_lib/state_space_control.i: c_lib/state_space_control.cpp.i

.PHONY : c_lib/state_space_control.i

# target to preprocess a source file
c_lib/state_space_control.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/state_space_control.cpp.i
.PHONY : c_lib/state_space_control.cpp.i

c_lib/state_space_control.s: c_lib/state_space_control.cpp.s

.PHONY : c_lib/state_space_control.s

# target to generate assembly for a file
c_lib/state_space_control.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/state_space_control.cpp.s
.PHONY : c_lib/state_space_control.cpp.s

c_lib/twimaster.o: c_lib/twimaster.cpp.o

.PHONY : c_lib/twimaster.o

# target to build an object file
c_lib/twimaster.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/twimaster.cpp.o
.PHONY : c_lib/twimaster.cpp.o

c_lib/twimaster.i: c_lib/twimaster.cpp.i

.PHONY : c_lib/twimaster.i

# target to preprocess a source file
c_lib/twimaster.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/twimaster.cpp.i
.PHONY : c_lib/twimaster.cpp.i

c_lib/twimaster.s: c_lib/twimaster.cpp.s

.PHONY : c_lib/twimaster.s

# target to generate assembly for a file
c_lib/twimaster.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/twimaster.cpp.s
.PHONY : c_lib/twimaster.cpp.s

c_lib/usb_debug_only.o: c_lib/usb_debug_only.cpp.o

.PHONY : c_lib/usb_debug_only.o

# target to build an object file
c_lib/usb_debug_only.cpp.o:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/usb_debug_only.cpp.o
.PHONY : c_lib/usb_debug_only.cpp.o

c_lib/usb_debug_only.i: c_lib/usb_debug_only.cpp.i

.PHONY : c_lib/usb_debug_only.i

# target to preprocess a source file
c_lib/usb_debug_only.cpp.i:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/usb_debug_only.cpp.i
.PHONY : c_lib/usb_debug_only.cpp.i

c_lib/usb_debug_only.s: c_lib/usb_debug_only.cpp.s

.PHONY : c_lib/usb_debug_only.s

# target to generate assembly for a file
c_lib/usb_debug_only.cpp.s:
	$(MAKE) -f CMakeFiles/Calculator-atmega32u4.dir/build.make CMakeFiles/Calculator-atmega32u4.dir/c_lib/usb_debug_only.cpp.s
.PHONY : c_lib/usb_debug_only.cpp.s

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.o: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.o

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.o

# target to build an object file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.o
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.o

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.o: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.o

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.o: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.o

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.o: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.o

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/Events.o: lufa/LUFA/Drivers/USB/Core/Events.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/Events.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.o

lufa/LUFA/Drivers/USB/Core/Events.i: lufa/LUFA/Drivers/USB/Core/Events.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/Events.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.i

lufa/LUFA/Drivers/USB/Core/Events.s: lufa/LUFA/Drivers/USB/Core/Events.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/Events.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.s

lufa/LUFA/Drivers/USB/Core/HostStandardReq.o: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.o

lufa/LUFA/Drivers/USB/Core/HostStandardReq.i: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/HostStandardReq.s: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/USBTask.o: lufa/LUFA/Drivers/USB/Core/USBTask.c.o

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.o

# target to build an object file
lufa/LUFA/Drivers/USB/Core/USBTask.c.o:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.o
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.o

lufa/LUFA/Drivers/USB/Core/USBTask.i: lufa/LUFA/Drivers/USB/Core/USBTask.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/USBTask.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.i

lufa/LUFA/Drivers/USB/Core/USBTask.s: lufa/LUFA/Drivers/USB/Core/USBTask.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/USBTask.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Calculator"
	@echo "... LUFA_USB"
	@echo "... rebuild_cache"
	@echo "... LUFA_USB-atmega32u4"
	@echo "... Calculator-atmega32u4"
	@echo "... erase_program"
	@echo "... c_lib/Battery_Monitor.o"
	@echo "... c_lib/Battery_Monitor.i"
	@echo "... c_lib/Battery_Monitor.s"
	@echo "... c_lib/Controller.o"
	@echo "... c_lib/Controller.i"
	@echo "... c_lib/Controller.s"
	@echo "... c_lib/EEPROM.o"
	@echo "... c_lib/EEPROM.i"
	@echo "... c_lib/EEPROM.s"
	@echo "... c_lib/Encoder.o"
	@echo "... c_lib/Encoder.i"
	@echo "... c_lib/Encoder.s"
	@echo "... c_lib/Filter.o"
	@echo "... c_lib/Filter.i"
	@echo "... c_lib/Filter.s"
	@echo "... c_lib/I2C_MPU6050.o"
	@echo "... c_lib/I2C_MPU6050.i"
	@echo "... c_lib/I2C_MPU6050.s"
	@echo "... c_lib/MEGN540_MessageHandeling.o"
	@echo "... c_lib/MEGN540_MessageHandeling.i"
	@echo "... c_lib/MEGN540_MessageHandeling.s"
	@echo "... c_lib/MPU6050.o"
	@echo "... c_lib/MPU6050.i"
	@echo "... c_lib/MPU6050.s"
	@echo "... c_lib/Matrix.o"
	@echo "... c_lib/Matrix.i"
	@echo "... c_lib/Matrix.s"
	@echo "... c_lib/MotorPWM.o"
	@echo "... c_lib/MotorPWM.i"
	@echo "... c_lib/MotorPWM.s"
	@echo "... c_lib/Ring_Buffer.o"
	@echo "... c_lib/Ring_Buffer.i"
	@echo "... c_lib/Ring_Buffer.s"
	@echo "... c_lib/SerialIO.o"
	@echo "... c_lib/SerialIO.i"
	@echo "... c_lib/SerialIO.s"
	@echo "... c_lib/Task_Management.o"
	@echo "... c_lib/Task_Management.i"
	@echo "... c_lib/Task_Management.s"
	@echo "... c_lib/Timing.o"
	@echo "... c_lib/Timing.i"
	@echo "... c_lib/Timing.s"
	@echo "... c_lib/USB_Config/Descriptors.o"
	@echo "... c_lib/USB_Config/Descriptors.i"
	@echo "... c_lib/USB_Config/Descriptors.s"
	@echo "... c_lib/ZoomieZumo.o"
	@echo "... c_lib/ZoomieZumo.i"
	@echo "... c_lib/ZoomieZumo.s"
	@echo "... c_lib/analog.o"
	@echo "... c_lib/analog.i"
	@echo "... c_lib/analog.s"
	@echo "... c_lib/print.o"
	@echo "... c_lib/print.i"
	@echo "... c_lib/print.s"
	@echo "... c_lib/state_space_control.o"
	@echo "... c_lib/state_space_control.i"
	@echo "... c_lib/state_space_control.s"
	@echo "... c_lib/twimaster.o"
	@echo "... c_lib/twimaster.i"
	@echo "... c_lib/twimaster.s"
	@echo "... c_lib/usb_debug_only.o"
	@echo "... c_lib/usb_debug_only.i"
	@echo "... c_lib/usb_debug_only.s"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.o"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.o"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

