# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mule/Documents/Calculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mule/Documents/Calculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mule/Documents/Calculator/CMakeFiles /home/mule/Documents/Calculator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mule/Documents/Calculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named disassemble_Calc

# Build rule for target.
disassemble_Calc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disassemble_Calc
.PHONY : disassemble_Calc

# fast build rule for target.
disassemble_Calc/fast:
	$(MAKE) -f CMakeFiles/disassemble_Calc.dir/build.make CMakeFiles/disassemble_Calc.dir/build
.PHONY : disassemble_Calc/fast

#=============================================================================
# Target rules for targets named upload_Calc_eeprom

# Build rule for target.
upload_Calc_eeprom: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_Calc_eeprom
.PHONY : upload_Calc_eeprom

# fast build rule for target.
upload_Calc_eeprom/fast:
	$(MAKE) -f CMakeFiles/upload_Calc_eeprom.dir/build.make CMakeFiles/upload_Calc_eeprom.dir/build
.PHONY : upload_Calc_eeprom/fast

#=============================================================================
# Target rules for targets named upload_Calc

# Build rule for target.
upload_Calc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload_Calc
.PHONY : upload_Calc

# fast build rule for target.
upload_Calc/fast:
	$(MAKE) -f CMakeFiles/upload_Calc.dir/build.make CMakeFiles/upload_Calc.dir/build
.PHONY : upload_Calc/fast

#=============================================================================
# Target rules for targets named Calc

# Build rule for target.
Calc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Calc
.PHONY : Calc

# fast build rule for target.
Calc/fast:
	$(MAKE) -f CMakeFiles/Calc.dir/build.make CMakeFiles/Calc.dir/build
.PHONY : Calc/fast

#=============================================================================
# Target rules for targets named Calc-atmega32u4.elf

# Build rule for target.
Calc-atmega32u4.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Calc-atmega32u4.elf
.PHONY : Calc-atmega32u4.elf

# fast build rule for target.
Calc-atmega32u4.elf/fast:
	$(MAKE) -f CMakeFiles/Calc-atmega32u4.elf.dir/build.make CMakeFiles/Calc-atmega32u4.elf.dir/build
.PHONY : Calc-atmega32u4.elf/fast

#=============================================================================
# Target rules for targets named CALCULATOR-atmega32u4

# Build rule for target.
CALCULATOR-atmega32u4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CALCULATOR-atmega32u4
.PHONY : CALCULATOR-atmega32u4

# fast build rule for target.
CALCULATOR-atmega32u4/fast:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/build
.PHONY : CALCULATOR-atmega32u4/fast

#=============================================================================
# Target rules for targets named LUFA_USB

# Build rule for target.
LUFA_USB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LUFA_USB
.PHONY : LUFA_USB

# fast build rule for target.
LUFA_USB/fast:
	$(MAKE) -f CMakeFiles/LUFA_USB.dir/build.make CMakeFiles/LUFA_USB.dir/build
.PHONY : LUFA_USB/fast

#=============================================================================
# Target rules for targets named LUFA_USB-atmega32u4

# Build rule for target.
LUFA_USB-atmega32u4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LUFA_USB-atmega32u4
.PHONY : LUFA_USB-atmega32u4

# fast build rule for target.
LUFA_USB-atmega32u4/fast:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/build
.PHONY : LUFA_USB-atmega32u4/fast

#=============================================================================
# Target rules for targets named CALCULATOR

# Build rule for target.
CALCULATOR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CALCULATOR
.PHONY : CALCULATOR

# fast build rule for target.
CALCULATOR/fast:
	$(MAKE) -f CMakeFiles/CALCULATOR.dir/build.make CMakeFiles/CALCULATOR.dir/build
.PHONY : CALCULATOR/fast

#=============================================================================
# Target rules for targets named erase_program

# Build rule for target.
erase_program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erase_program
.PHONY : erase_program

# fast build rule for target.
erase_program/fast:
	$(MAKE) -f CMakeFiles/erase_program.dir/build.make CMakeFiles/erase_program.dir/build
.PHONY : erase_program/fast

Calc.obj: Calc.cpp.obj

.PHONY : Calc.obj

# target to build an object file
Calc.cpp.obj:
	$(MAKE) -f CMakeFiles/Calc-atmega32u4.elf.dir/build.make CMakeFiles/Calc-atmega32u4.elf.dir/Calc.cpp.obj
.PHONY : Calc.cpp.obj

Calc.i: Calc.cpp.i

.PHONY : Calc.i

# target to preprocess a source file
Calc.cpp.i:
	$(MAKE) -f CMakeFiles/Calc-atmega32u4.elf.dir/build.make CMakeFiles/Calc-atmega32u4.elf.dir/Calc.cpp.i
.PHONY : Calc.cpp.i

Calc.s: Calc.cpp.s

.PHONY : Calc.s

# target to generate assembly for a file
Calc.cpp.s:
	$(MAKE) -f CMakeFiles/Calc-atmega32u4.elf.dir/build.make CMakeFiles/Calc-atmega32u4.elf.dir/Calc.cpp.s
.PHONY : Calc.cpp.s

c_lib/KeypadMatrix.obj: c_lib/KeypadMatrix.cpp.obj

.PHONY : c_lib/KeypadMatrix.obj

# target to build an object file
c_lib/KeypadMatrix.cpp.obj:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/KeypadMatrix.cpp.obj
.PHONY : c_lib/KeypadMatrix.cpp.obj

c_lib/KeypadMatrix.i: c_lib/KeypadMatrix.cpp.i

.PHONY : c_lib/KeypadMatrix.i

# target to preprocess a source file
c_lib/KeypadMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/KeypadMatrix.cpp.i
.PHONY : c_lib/KeypadMatrix.cpp.i

c_lib/KeypadMatrix.s: c_lib/KeypadMatrix.cpp.s

.PHONY : c_lib/KeypadMatrix.s

# target to generate assembly for a file
c_lib/KeypadMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/KeypadMatrix.cpp.s
.PHONY : c_lib/KeypadMatrix.cpp.s

c_lib/LCD.obj: c_lib/LCD.cpp.obj

.PHONY : c_lib/LCD.obj

# target to build an object file
c_lib/LCD.cpp.obj:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/LCD.cpp.obj
.PHONY : c_lib/LCD.cpp.obj

c_lib/LCD.i: c_lib/LCD.cpp.i

.PHONY : c_lib/LCD.i

# target to preprocess a source file
c_lib/LCD.cpp.i:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/LCD.cpp.i
.PHONY : c_lib/LCD.cpp.i

c_lib/LCD.s: c_lib/LCD.cpp.s

.PHONY : c_lib/LCD.s

# target to generate assembly for a file
c_lib/LCD.cpp.s:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/LCD.cpp.s
.PHONY : c_lib/LCD.cpp.s

c_lib/Timing.obj: c_lib/Timing.cpp.obj

.PHONY : c_lib/Timing.obj

# target to build an object file
c_lib/Timing.cpp.obj:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/Timing.cpp.obj
.PHONY : c_lib/Timing.cpp.obj

c_lib/Timing.i: c_lib/Timing.cpp.i

.PHONY : c_lib/Timing.i

# target to preprocess a source file
c_lib/Timing.cpp.i:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/Timing.cpp.i
.PHONY : c_lib/Timing.cpp.i

c_lib/Timing.s: c_lib/Timing.cpp.s

.PHONY : c_lib/Timing.s

# target to generate assembly for a file
c_lib/Timing.cpp.s:
	$(MAKE) -f CMakeFiles/CALCULATOR-atmega32u4.dir/build.make CMakeFiles/CALCULATOR-atmega32u4.dir/c_lib/Timing.cpp.s
.PHONY : c_lib/Timing.cpp.s

c_lib/USB_Config/Descriptors.obj: c_lib/USB_Config/Descriptors.c.obj

.PHONY : c_lib/USB_Config/Descriptors.obj

# target to build an object file
c_lib/USB_Config/Descriptors.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.obj
.PHONY : c_lib/USB_Config/Descriptors.c.obj

c_lib/USB_Config/Descriptors.i: c_lib/USB_Config/Descriptors.c.i

.PHONY : c_lib/USB_Config/Descriptors.i

# target to preprocess a source file
c_lib/USB_Config/Descriptors.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.i
.PHONY : c_lib/USB_Config/Descriptors.c.i

c_lib/USB_Config/Descriptors.s: c_lib/USB_Config/Descriptors.c.s

.PHONY : c_lib/USB_Config/Descriptors.s

# target to generate assembly for a file
c_lib/USB_Config/Descriptors.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/c_lib/USB_Config/Descriptors.c.s
.PHONY : c_lib/USB_Config/Descriptors.c.s

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.obj

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.i

lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s: lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s
.PHONY : lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.obj

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.i

lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s: lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c.s

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.obj

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.i

lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s: lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.c.s

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.obj

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s: lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/Events.obj: lufa/LUFA/Drivers/USB/Core/Events.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/Events.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.obj

lufa/LUFA/Drivers/USB/Core/Events.i: lufa/LUFA/Drivers/USB/Core/Events.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/Events.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.i

lufa/LUFA/Drivers/USB/Core/Events.s: lufa/LUFA/Drivers/USB/Core/Events.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/Events.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/Events.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/Events.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/Events.c.s

lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.obj

lufa/LUFA/Drivers/USB/Core/HostStandardReq.i: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.i

lufa/LUFA/Drivers/USB/Core/HostStandardReq.s: lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/HostStandardReq.c.s

lufa/LUFA/Drivers/USB/Core/USBTask.obj: lufa/LUFA/Drivers/USB/Core/USBTask.c.obj

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.obj

# target to build an object file
lufa/LUFA/Drivers/USB/Core/USBTask.c.obj:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.obj
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.obj

lufa/LUFA/Drivers/USB/Core/USBTask.i: lufa/LUFA/Drivers/USB/Core/USBTask.c.i

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.i

# target to preprocess a source file
lufa/LUFA/Drivers/USB/Core/USBTask.c.i:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.i
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.i

lufa/LUFA/Drivers/USB/Core/USBTask.s: lufa/LUFA/Drivers/USB/Core/USBTask.c.s

.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.s

# target to generate assembly for a file
lufa/LUFA/Drivers/USB/Core/USBTask.c.s:
	$(MAKE) -f CMakeFiles/LUFA_USB-atmega32u4.dir/build.make CMakeFiles/LUFA_USB-atmega32u4.dir/lufa/LUFA/Drivers/USB/Core/USBTask.c.s
.PHONY : lufa/LUFA/Drivers/USB/Core/USBTask.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... disassemble_Calc"
	@echo "... upload_Calc_eeprom"
	@echo "... upload_Calc"
	@echo "... Calc"
	@echo "... Calc-atmega32u4.elf"
	@echo "... CALCULATOR-atmega32u4"
	@echo "... LUFA_USB"
	@echo "... rebuild_cache"
	@echo "... LUFA_USB-atmega32u4"
	@echo "... CALCULATOR"
	@echo "... erase_program"
	@echo "... Calc.obj"
	@echo "... Calc.i"
	@echo "... Calc.s"
	@echo "... c_lib/KeypadMatrix.obj"
	@echo "... c_lib/KeypadMatrix.i"
	@echo "... c_lib/KeypadMatrix.s"
	@echo "... c_lib/LCD.obj"
	@echo "... c_lib/LCD.i"
	@echo "... c_lib/LCD.s"
	@echo "... c_lib/Timing.obj"
	@echo "... c_lib/Timing.i"
	@echo "... c_lib/Timing.s"
	@echo "... c_lib/USB_Config/Descriptors.obj"
	@echo "... c_lib/USB_Config/Descriptors.i"
	@echo "... c_lib/USB_Config/Descriptors.s"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.obj"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.i"
	@echo "... lufa/LUFA/Drivers/USB/Class/Common/HIDParser.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/ConfigDescriptors.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/Events.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/HostStandardReq.s"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.obj"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.i"
	@echo "... lufa/LUFA/Drivers/USB/Core/USBTask.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

